language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - "sudo apt-get install libffi"
  - "pip install ."
  - "pip install -r test_requirements.txt"
script: py.test -n 4 --cov pycohttpparser test.py
