language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - "sudo apt-get install libffi-dev python-dev"
  - "pip install ."
  - "pip install -r test_requirements.txt"
script: py.test --cov pycohttpparser test.py
