language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

sudo: false
addons:
  apt:
    packages:
      - libffi-dev
      - python-dev
install: "./.travis/install.sh"
before_script: "flake8 --max-complexity 10 src/ test.py"
script: py.test --cov pycohttpparser test.py
